name: Update README

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate GitHub Stats and Update README
      uses: anuraghazra/github-readme-stats@latest
      with:
        username: milenaabernardi
        show_icons: true
        theme: tokyonight
        include_all_commits: true
        count_private: true
        border_color: '00000000'

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update README with new stats"
        git push
